### ISSUE TITLE
Change Presentation of House Accomplishments in 5.C.1

### ISSUE THREAD

**Issue by rhochgraf21** [rhochgraf21/Constitution#10]
Check one:
- [X] Semantic Issue: something about the meaning of the text is different
- [ ] Non-semantic Issue: Spelling, grammar, or formatting changes.

Summary of issue:

According to 5.C.1, section i, eboard is expected: `To publish a document at the end of each semester to all Members stating House’s accomplishments of that semester`. My understanding is that the current practice is to publish this document annually.

I see two main routes of modification (there may be others as well):
- change this to be one presentation per year, matching current practice.
- remove this requirement, and let this live as tradition/precedent rather than a requirement.

**Comment by esoccoli** [comment]
Decided to leave it as is
