### ISSUE TITLE
5.B Add voting or non-voting to responsibilities section of each eboard member

### ISSUE THREAD

**Issue by esoccoli** [rhochgraf21/Constitution#122]
Check one:
- [ ] Semantic Issue: something about the meaning of the text is different
- [x] Non-semantic Issue: Spelling, grammar, or formatting changes.

Summary of issue:
Since we removed the list of directors, we should specify somewhere which members are voting and which are non-voting, and responsibilities section seems like a good place.

Could add a bullet point to voting members saying something along the lines of "Vote on issues presented to eboard"

**Comment by mxmeinhold** [comment]
Please don't make this a separate change. It functionally breaks the constitution, and these two should be linked. I am of the opinion that the list is more convenient a reference, it also provides a definition for the terms Voting and Non Voting

**Comment by esoccoli** [comment]
I combined this change with removing list of directorships
