### ISSUE TITLE
Reorganize Constitution Sections

### ISSUE THREAD

**Issue by rhochgraf21** [rhochgraf21/Constitution#13]
Check one:
- [X] Semantic Issue: something about the meaning of the text is different
- [x] Non-semantic Issue: Spelling, grammar, or formatting changes.

Summary of issue:

needs discussion

the early draft included the following sections:

- Introduction
- Structure
- Membership
- Officers of the House
- General Operations of the House
- Voting
- Modifications to the Constitution
- Judicial
- Adherence to University Policy

This included three major refactors:

1 - moving Packet and Evaluations into the Membership section
2 - moving operations of the Evaluations/Financial directorships into "General Operations of the House"
3 - moving maintainers and RTPs under "Officers of the House"

this has the benefit of increasing the cohesion of each section, so that each section is more closely related to a single task

**Comment by esoccoli** [comment]
I have some thoughts about this.

From what we have gotten through so far, it seems like we are going to want to do a bunch of reorganizing of stuff, and I don't think it makes sense to actually move stuff until the end, so I think it would make sense to have a megathread for any organization changes that we might want to make, and then we can go through it at the end, right before we check for spelling/grammar/internal consistency.

Additionally, I was thinking that it would probably be useful to have an outline of what we want the final structure to look like, and update that as we go (which I can deal with), in addition to putting stuff in a megathread. This way, once we get to the point where we are ready to actually do the reorganization, we already have an outline made and we just have to insert content into the proper sections.

**Comment by esoccoli** [comment]
Will be addressed with spelling, grammar, and internal consistency (#28 )
