### ISSUE TITLE
How to handle the usage of the word "ballot"

### ISSUE THREAD

**Issue by esoccoli** [rhochgraf21/Constitution#140]
Check one:
- [ ] Semantic Issue: something about the meaning of the text is different
- [ ] Non-semantic Issue: Spelling, grammar, or formatting changes.

Summary of issue:
The use of the word "ballot" implies that we vote on paper, which is not what we actually do. We need to either replace all instances of the word "ballot" with something else, or define "ballot" in a way that allows for methods of voting other than voting using paper ballots

**Comment by danisaba** [comment]
define ballot in definitions section as "a method of vote" or some other thing that makes it good smile
