### ISSUE TITLE
7.D Create a clause that will require public Judicials to be recorded as case law 

### ISSUE THREAD

**Issue by IgorPolotai** [rhochgraf21/Constitution#146]
Check one:
- [X] Semantic Issue: something about the meaning of the text is different
- [ ] Non-semantic Issue: Spelling, grammar, or formatting changes.

Summary of issue:
Create a new 7.D that will require an Eboard member to record all public Judicials in a public documents accessible by all CSHers, and record all private Judicials in a private document only accessible to past, present, and future Eboard members.

**Comment by mxmeinhold** [comment]
Rather than "case law", would it be possible to reuse existing language surrounding notes?

**Comment by esoccoli** [comment]
This will be handled in its own amendment, after we finish the rewrite

**Comment by esoccoli** [comment]
Closing this for now, we will come back and discuss this issue after we pass the rewrite
