### ISSUE TITLE
Remove "Note" and "Additional Note" from 5.D.2.B.1 and 5.D.2.B.2

### ISSUE THREAD

**Issue by IgorPolotai** [rhochgraf21/Constitution#156]
Check one:
- [ ] Semantic Issue: something about the meaning of the text is different
- [X] Non-semantic Issue: Spelling, grammar, or formatting changes.

Summary of issue: Remove the words Note and Additional Note, as they serve few purposes, and make the document more sloppy looking

**Comment by Sam-Cordry** [comment]
Should put the content of "Note" and "Additional Note" directly under 5.D.2.B,
