### ISSUE TITLE
Table Of Contents - Add Purpose and Definitions to Abbreviations and Definitions [From Robert's Notes]

### ISSUE THREAD

**Issue by IgorPolotai** [rhochgraf21/Constitution#167]
Check one:
- [ ] Semantic Issue: something about the meaning of the text is different
- [x] Non-semantic Issue: Spelling, grammar, or formatting changes.

Summary of issue: Add a Purpose Section and a Definitions Section under II Abbreviations and Definitions in the Table Of Contents on Page 1

**Comment by esoccoli** [comment]
What content would we put there?

**Comment by esoccoli** [comment]
addressed by #216 with the addition of a definitions section to go with abbreviations
