### ISSUE TITLE
Article II - Needs subsections 2.A and 2.B [From Robert's Notes]

### ISSUE THREAD

**Issue by IgorPolotai** [rhochgraf21/Constitution#169]
Check one:
- [ ] Semantic Issue: something about the meaning of the text is different
- [x] Non-semantic Issue: Spelling, grammar, or formatting changes.

Summary of issue: Add a subsection 2.A in front of the line "Many of the commonly used abbreviations...", and a subsection 2.B before the abbreviations.

**Comment by esoccoli** [comment]
I believe we decided to just remove the sentence before the list of abbreviations, because it is redundant, and the title + content conveys what needs to be conveyed

**Comment by esoccoli** [comment]
I removed the sentence before the abbreviations list, and split it into a subsection for abbreviations, and another subsection for definitions

**Comment by esoccoli** [comment]
addressed by #216
