### ISSUE TITLE
It Appears RTPs Cannot Quit Without Leaving Active Membership (5.D.3)

### ISSUE THREAD

**Issue by rhochgraf21** [rhochgraf21/Constitution#17]
Check one:
- [X] Semantic Issue: something about the meaning of the text is different
- [ ] Non-semantic Issue: Spelling, grammar, or formatting changes.

Summary of issue:

It appears that RTPs cannot...quit. It might be nice to include language that allows resignation from an RTP position.

(eg: "linux, the gift that keeps on taking" - Loerb01)

See 5.D.3

**Comment by mxmeinhold** [comment]
Resignation of an RTP is a very complicated technical process, though you might define a way to move out of active rtp status. That said, that is only a relavent process if there's a quorum or similar keyed off it I think

**Comment by rhochgraf21** [comment]
Discussion with RTPs yielded conclusion that RTPs do not need a mechanism to quit, as they can simply stop doing RTP contributions at any time. We're not planning to address this in this revision.
