### ISSUE TITLE
Article II - Turn abbreviations into an alphabetically sorted table [From Robert's Notes]

### ISSUE THREAD

**Issue by IgorPolotai** [rhochgraf21/Constitution#170]
Check one:
- [ ] Semantic Issue: something about the meaning of the text is different
- [x] Non-semantic Issue: Spelling, grammar, or formatting changes.

Summary of issue: Turn the list of abbreviations into a table that has four columns:

Name                 Abbrev     Name                Abbrev
Chairperson     Chair        Evaluations      Evals

etc

**Comment by esoccoli** [comment]
Why 4 columns instead of 2?

**Comment by esoccoli** [comment]
addressed by #216
