### ISSUE TITLE
Article III - Rename Constitutional Structure to Operating Session [From Robert's Notes]

### ISSUE THREAD

**Issue by IgorPolotai** [rhochgraf21/Constitution#171]
Check one:
- [x] Semantic Issue: something about the meaning of the text is different
- [ ] Non-semantic Issue: Spelling, grammar, or formatting changes.

Summary of issue: Change the title of Constitutional Structure to Operating Session

**Comment by esoccoli** [comment]
Decided to move the definition of Standard Operating Session to the definitions table, and then removed that subsection from here.

**Comment by esoccoli** [comment]
Decided to move standard operating session to definitions
