### ISSUE TITLE
Article III - Add subsection 3.C: Membership Agreements [From Robert's Notes]

### ISSUE THREAD

**Issue by IgorPolotai** [rhochgraf21/Constitution#172]
Check one:
- [ ] Semantic Issue: something about the meaning of the text is different
- [x] Non-semantic Issue: Spelling, grammar, or formatting changes.

Summary of issue: Add Membership Agreements to the end of Article III

**Comment by esoccoli** [comment]
This feels like something that would need to be done in a separate amendment
