### ISSUE TITLE
4.A.1 - Change "Introductory" to "Intro" [From Robert's Notes]

### ISSUE THREAD

**Issue by IgorPolotai** [rhochgraf21/Constitution#173]
Check one:
- [ ] Semantic Issue: something about the meaning of the text is different
- [x] Non-semantic Issue: Spelling, grammar, or formatting changes.

Summary of issue: To keep consistent with "Intro Membership is open to all RIT students", change the title of the subsection 4.A.1 to "Intro Membership Qualifications"

**Comment by esoccoli** [comment]
After discussion, we decided to not use any abbreviations in section titles
