### ISSUE TITLE
4.A.2.A.1 - Move the Note to section 4.A.4, and delete the "Additional Note" sentence [From Robert's Notes]

### ISSUE THREAD

**Issue by IgorPolotai** [rhochgraf21/Constitution#174]
Check one:
- [ ] Semantic Issue: something about the meaning of the text is different
- [x] Non-semantic Issue: Spelling, grammar, or formatting changes.

Summary of issue: Move the Note paragraph in section 4.A.2.A.1 to 4.A.4, and delete the Additional Note sentence from this section.

**Comment by esoccoli** [comment]
addressed by #216
