### ISSUE TITLE
4.A.3 and 4.A.4 - Rename Introductory to Intro in subsection titles [From Robert's Notes]

### ISSUE THREAD

**Issue by IgorPolotai** [rhochgraf21/Constitution#176]
Check one:
- [ ] Semantic Issue: something about the meaning of the text is different
- [x] Non-semantic Issue: Spelling, grammar, or formatting changes.

Summary of issue: Same reasoning as in Issue #173

**Comment by esoccoli** [comment]
After discussion, we decided to not use any abbreviations in section titles
