### ISSUE TITLE
4.A.7 - Missing Vote Quorum for extending the intro process [From Robert's Notes]

### ISSUE THREAD

**Issue by IgorPolotai** [rhochgraf21/Constitution#178]
Check one:
- [x] Semantic Issue: something about the meaning of the text is different
- [ ] Non-semantic Issue: Spelling, grammar, or formatting changes.

Summary of issue: Add a vote Quorum for extending the intro process for this subsection

**Comment by esoccoli** [comment]
addressed by #216
