### ISSUE TITLE
4.A.8.A - Make signing a Membership Agreement an active member requirement & qualification [From Robert's Notes]

### ISSUE THREAD

**Issue by IgorPolotai** [rhochgraf21/Constitution#179]
Check one:
- [x] Semantic Issue: something about the meaning of the text is different
- [ ] Non-semantic Issue: Spelling, grammar, or formatting changes.

Summary of issue: You can be a member without signing the agreement. We should make this an active member requirement + qualification.

**Comment by esoccoli** [comment]
This seems to be covered by #181

**Comment by esoccoli** [comment]
addressed by #216
