### ISSUE TITLE
4.B.1 - Add signing Membership Agreement as a requirement for Active Membership [From Robert's Notes]

### ISSUE THREAD

**Issue by IgorPolotai** [rhochgraf21/Constitution#181]
Check one:
- [x] Semantic Issue: something about the meaning of the text is different
- [ ] Non-semantic Issue: Spelling, grammar, or formatting changes.

Summary of issue: Add the requirement of signing the Membership Agreement as a requirement for Active Membership

**Comment by esoccoli** [comment]
addressed by #216
