### ISSUE TITLE
4.B.4 - Change "Reside on the House" to something else [From Robert's Notes]

### ISSUE THREAD

**Issue by IgorPolotai** [rhochgraf21/Constitution#183]
Check one:
- [x] Semantic Issue: something about the meaning of the text is different
- [ ] Non-semantic Issue: Spelling, grammar, or formatting changes.

Summary of issue: Reside is defined as "to have one's permanent home in a particular place." We do not give this privilege to off-floor members and other membership can can also reside on floor.

**Comment by esoccoli** [comment]
addressed by #216
