### ISSUE TITLE
4.B.4.A - Change or remove line about requiring attending on House social event [From Robert's Notes]

### ISSUE THREAD

**Issue by IgorPolotai** [rhochgraf21/Constitution#186]
Check one:
- [x] Semantic Issue: something about the meaning of the text is different
- [ ] Non-semantic Issue: Spelling, grammar, or formatting changes.

Summary of issue: Since we do not check for this, this line should be changed or removed.

**Comment by esoccoli** [comment]
We do check for this, but not officially through attendance. Intro members submit a form where they list the social events they have attended

**Comment by esoccoli** [comment]
Decided not to pursue this change (we want to keep that requirement, bc we do check it, just not through attendance)
