### ISSUE TITLE
4.B.4.A - Change line about attending two seminars relating to computing or electronics [From Robert's Notes]

### ISSUE THREAD

**Issue by IgorPolotai** [rhochgraf21/Constitution#187]
Check one:
- [x] Semantic Issue: something about the meaning of the text is different
- [ ] Non-semantic Issue: Spelling, grammar, or formatting changes.

Summary of issue: Since technical seminars can be varied, change this line to potentially be at "R&D's Discretion".

**Comment by esoccoli** [comment]
addressed by #216
