### ISSUE TITLE
4.B.5.A.1.A - Entire subsection is awkward and uses old voting language [From Robert's Notes]

### ISSUE THREAD

**Issue by IgorPolotai** [rhochgraf21/Constitution#188]
Check one:
- [x] Semantic Issue: something about the meaning of the text is different
- [ ] Non-semantic Issue: Spelling, grammar, or formatting changes.

Summary of issue: The subsection still uses old voting language such a as Total Number of Possible Votes, and is generally awkward.

**Comment by esoccoli** [comment]
addressed by #216
