### ISSUE TITLE
4.B.5.A.1.B - Remove the line "In either case, the member forfeits their ability to be included on the following year's roster." [From Robert's Notes]

### ISSUE THREAD

**Issue by IgorPolotai** [rhochgraf21/Constitution#189]
Check one:
- [x] Semantic Issue: something about the meaning of the text is different
- [ ] Non-semantic Issue: Spelling, grammar, or formatting changes.

Summary of issue: HOUSING BOARD? - Is this what we want???

no other notes from Robert

**Comment by esoccoli** [comment]
addressed by #216
