### ISSUE TITLE
4.B.5.A.2 - Potentially change "any" [From Robert's Notes]

### ISSUE THREAD

**Issue by IgorPolotai** [rhochgraf21/Constitution#190]
Check one:
- [x] Semantic Issue: something about the meaning of the text is different
- [ ] Non-semantic Issue: Spelling, grammar, or formatting changes.

Summary of issue: "If a member disagrees with the outcome of any evaluation...and wishes to appeal the decision, they may do so as stated in 5.D" implies that any member can challenge the result of any evaluation, thus Eboard can retcon any member. Dani previously said that we can't remove members from the org for "bullying", so change the word any.

**Comment by Sam-Cordry** [comment]
The wording of our change to fix this issue could have major ramifications, so this should be a separate amendment so that House can discuss this point individually.

**Comment by esoccoli** [comment]
After discussion, we decided that this change can be done here by changing it to saying "any failing eval"
