### ISSUE TITLE
4.D.3.b - Specify whether the Evals Director *has* to perform research, and to who they present their findings [From Robert's Notes]

### ISSUE THREAD

**Issue by IgorPolotai** [rhochgraf21/Constitution#191]
Check one:
- [x] Semantic Issue: something about the meaning of the text is different
- [ ] Non-semantic Issue: Spelling, grammar, or formatting changes.

Summary of issue: Specify in point b in 4.D.3 whether the Evals Director *has* to do preliminary research, and to who (Eboard or House) they have to present their findings.

**Comment by esoccoli** [comment]
Decided to leave the text as is.
