### ISSUE TITLE
5.A.1.A - Specify how Eboard maintains records of goals of previous Eboards [From Robert's Notes]

### ISSUE THREAD

**Issue by IgorPolotai** [rhochgraf21/Constitution#192]
Check one:
- [x] Semantic Issue: something about the meaning of the text is different
- [ ] Non-semantic Issue: Spelling, grammar, or formatting changes.

Summary of issue: Specify how Eboard maintains records of the goals defined by each previous Eboard

**Comment by esoccoli** [comment]
Decided not to pursue this change
