### ISSUE TITLE
5.A.1.A - Remove point j about reviewing the Constitution [From Robert's Notes]

### ISSUE THREAD

**Issue by IgorPolotai** [rhochgraf21/Constitution#193]
Check one:
- [x] Semantic Issue: something about the meaning of the text is different
- [ ] Non-semantic Issue: Spelling, grammar, or formatting changes.

Summary of issue: Change the requirement of Eboard "to review and update the Constitution at the end of each Standard Operating Session, as defined in 3.B" to be a Constitutional Maintainer responsibility.

**Comment by esoccoli** [comment]
addressed by #216
