### ISSUE TITLE
5.A.1.A - Add point k: "To preside over their respective meetings" [From Robert's Notes]

### ISSUE THREAD

**Issue by IgorPolotai** [rhochgraf21/Constitution#194]
Check one:
- [x] Semantic Issue: something about the meaning of the text is different
- [ ] Non-semantic Issue: Spelling, grammar, or formatting changes.

Summary of issue: Ensure Eboard directors have to preside over their meetings.

Editor's Note (from Igor): Does this imply that Chair's meeting is Eboard Meeting, meaning they are now Constitutionally required?

Editor's Editor Note: Nvm, me did not read the next section

**Comment by esoccoli** [comment]
addressed by #216
