### ISSUE TITLE
5.A - Remove all lines in each Director's individual responsibilities about presiding over their meetings [From Robert's Notes]

### ISSUE THREAD

**Issue by IgorPolotai** [rhochgraf21/Constitution#195]
Check one:
- [x] Semantic Issue: something about the meaning of the text is different
- [ ] Non-semantic Issue: Spelling, grammar, or formatting changes.

Summary of issue: In 5.A.2, 5.A.2.A, 5.A.2.B, 5.A.3, 5.A.3.A, 5.A.4, 5.A.5, 5.A.6, and 5.A.7, remove all references about them having to preside over their respective meetings (and move it to Eboard responsibilities overall. See Issue #194)

**Comment by esoccoli** [comment]
addressed by #216
