### ISSUE TITLE
5.D - Change the first line of section [From Robert's Notes]

### ISSUE THREAD

**Issue by IgorPolotai** [rhochgraf21/Constitution#199]
Check one:
- [x] Semantic Issue: something about the meaning of the text is different
- [ ] Non-semantic Issue: Spelling, grammar, or formatting changes.

Summary of issue: Delete the words "made by the Executive Board" in the sentence "Decisions made by the Executive Board may be appealed and overturned."

Editor's Note (from Igor): Then we should define what "decisions" means, and which can be appealed.

**Comment by esoccoli** [comment]
Resolved by #216
