### ISSUE TITLE
5.E.3 - Simplify the subsection by condensing it [From Robert's Notes]

### ISSUE THREAD

**Issue by IgorPolotai** [rhochgraf21/Constitution#200]
Check one:
- [x] Semantic Issue: something about the meaning of the text is different
- [ ] Non-semantic Issue: Spelling, grammar, or formatting changes.

Summary of issue: Change the current paragraph by condensing it: "Maintainer status lasts until [resigned or revoked]...If a Maintainer no longer satisfies 5.E.1, [their status is revoked]."

**Comment by esoccoli** [comment]
Resolved in #216
