### ISSUE TITLE
5.F.1.a - Delete "meeting the selection criteria in 5.F.1.A" [From Robert's Notes]

### ISSUE THREAD

**Issue by IgorPolotai** [rhochgraf21/Constitution#202]
Check one:
- [x] Semantic Issue: something about the meaning of the text is different
- [ ] Non-semantic Issue: Spelling, grammar, or formatting changes.

Summary of issue: Delete the reference from point a of 5.F.1

**Comment by esoccoli** [comment]
Resolved with #216
