### ISSUE TITLE
5.F.1.A - Delete all of 5.F.1.A [From Robert's Notes]

### ISSUE THREAD

**Issue by IgorPolotai** [rhochgraf21/Constitution#204]
Check one:
- [x] Semantic Issue: something about the meaning of the text is different
- [ ] Non-semantic Issue: Spelling, grammar, or formatting changes.

Summary of issue: Delete all of 5.F.1.A

**Comment by esoccoli** [comment]
Change qualification section to just be active members, and add a section below for prior rtps
