### ISSUE TITLE
5.F.1.C.1 - Add point d: "Maintainers may make non-semantic changes with approvals of two RTPs." [From Robert's Notes]

### ISSUE THREAD

**Issue by IgorPolotai** [rhochgraf21/Constitution#205]
Check one:
- [x] Semantic Issue: something about the meaning of the text is different
- [ ] Non-semantic Issue: Spelling, grammar, or formatting changes.

Summary of issue: Add a new point to 5.F.1.C.1 that allows Maintainers to make non-semantic changes to the COC

**Comment by esoccoli** [comment]
After discussion in meeting, we decided that RTPs (and not constitutional maintainers) should be able to make non semantic changes with the approval of 2 other RTPs.
