### ISSUE TITLE
6.A.2.A - Simply entire paragraph [From Robert's Notes]

### ISSUE THREAD

**Issue by IgorPolotai** [rhochgraf21/Constitution#206]
Check one:
- [x] Semantic Issue: something about the meaning of the text is different
- [ ] Non-semantic Issue: Spelling, grammar, or formatting changes.

Summary of issue: Simplify the entire paragraph. Something like "The Financial or Eboard can extend or reduce dues." Make bulk one line.

**Comment by esoccoli** [comment]
This seems like a pretty significant change, because it changes the process for getting a dues extension/reduction. If we wanted to pursue this, it would need to be done in a separate amendment later.

**Comment by esoccoli** [comment]
After a bit of discussion, the concensus was that if we word it in the right way, this can be done here without any changes to process, so I am reopening this
