### ISSUE TITLE
6.A.4 - Simplify expenditures by increasing single expenditures to $100 [From Robert's Notes]

### ISSUE THREAD

**Issue by IgorPolotai** [rhochgraf21/Constitution#208]
Check one:
- [x] Semantic Issue: something about the meaning of the text is different
- [ ] Non-semantic Issue: Spelling, grammar, or formatting changes.

Summary of issue: Remove the confusion between what single expenditures (which are limited to $75 without a Spending Presentation) and a total expenditure (which are limited to $100 without a Spending Presentation) by increasing single expenditures limit to $100. Simply the paragraph as needed.

**Comment by esoccoli** [comment]
I think this would have to be a separate amendment

**Comment by esoccoli** [comment]
Closing for now, we can discuss again later if we think we may want to make this change
