### ISSUE TITLE
6.B.1 - Fix Bug [From Robert's Notes]

### ISSUE THREAD

**Issue by IgorPolotai** [rhochgraf21/Constitution#210]
Check one:
- [?] Semantic Issue: something about the meaning of the text is different
- [?] Non-semantic Issue: Spelling, grammar, or formatting changes.

Summary of issue: 

????????????

Probably related to alumni keeping the ability to reserve rooms?

**Comment by esoccoli** [comment]
cc @Qelxiros is this something that we still allow
