### ISSUE TITLE
Update Vote Counters Section (6.A.6)

### ISSUE THREAD

**Issue by Sam-Cordry** [rhochgraf21/Constitution#31]
Check one:
- [x] Semantic Issue: something about the meaning of the text is different
- [ ] Non-semantic Issue: Spelling, grammar, or formatting changes.

Summary of issue:
6.A.6 states that the Chair of the Vote `will additionally select two other members to count votes`. This no longer reflects current practice. Either this language needs to be soften to allow for additional vote counters to be optional or vote counters should be removed from the Constitution altogether.

**Comment by mxmeinhold** [comment]
This isn't current practice? The chair is doing counting alone?

**Comment by Sam-Cordry** [comment]
Yes, that's correct. The use of Vote Counters is no longer current practice.

**Comment by mxmeinhold** [comment]
Is this in reference to the use of Vote, e.g.?

I would highly reccomend against removing vote counters entirely, as in any case that there occurs a paper or in person vote, having the triple count has been necessary error checking a number of times

**Comment by Sam-Cordry** [comment]
It's not directly in reference to Vote, it's also in reference to all votes (including in-person) we've held in at least the past year (and seemingly in years before that). I would agree with that, and I personally prefer softening the language (and I think that's what will happen). I'm leaving it up to discussion so that myself or a couple of us isn't making the decision unilaterally.

**Comment by mxmeinhold** [comment]
This also sounds like a chance to reform current practice for in person or paper votes then, if vote counters haven't been used. I can tell you they were consistent up to and into the pandemic, when we had 3 people doing vote counts in google sheets over discord.

**Comment by Sam-Cordry** [comment]
Yes, we're planning to do a larger reform for voting as a part of this rewrite, but we still need to talk more about how we're going to do that as a whole. From what I understand, Vote Counters more or less haven't been used since the pandemic.

**Comment by mxmeinhold** [comment]
Oh, you misread or I misstated. I meant that noticing this now is an opportunity to use vote counters as proscribed going forward

**Comment by Sam-Cordry** [comment]
Oh sorry, I think I misunderstood or misread. Yes, that is certainly on the table for when we're in discussion with the rest of House about it.
