### ISSUE TITLE
2.B ResLife reviews constitution annually

### ISSUE THREAD

**Issue by esoccoli** [rhochgraf21/Constitution#35]
Check one:
- [ ] Semantic Issue: something about the meaning of the text is different
- [ ] Non-semantic Issue: Spelling, grammar, or formatting changes.

Summary of issue:
Constitution states that reslife reviews the constitution each year. Do we know if this is actually the case?

**Comment by jabbate19** [comment]
They do it much less frequent. ResLife has told us they’re gonna do it eventually for many years.

**Comment by rhochgraf21** [comment]
Question has been answered, closing issue as stale.
