### ISSUE TITLE
Membership Evaluations Occur Only Once A Year (5.C.3(d))

### ISSUE THREAD

**Issue by esoccoli** [rhochgraf21/Constitution#36]
Check one:
- [X] Semantic Issue: something about the meaning of the text is different
- [ ] Non-semantic Issue: Spelling, grammar, or formatting changes.

Summary of issue:
The constitution still states that active members are evaluated semi annually, and has not been updated since winter evaluations stopped happening.

**Comment by Sam-Cordry** [comment]
So 5.D.2.C implies that the Semi-Annual Evaluations is the same as the Introductory Evaluation. So what I'll go ahead and do here is make a draft to clarify the language in 5.C.3 and 5.D.2.C to make it more consistent with the use of the term "Introductory Evaluation".
