### ISSUE TITLE
Refactor Article VI, Voting

### ISSUE THREAD

**Issue by rhochgraf21** [rhochgraf21/Constitution#37]
Check one:
- [X] Semantic Issue: something about the meaning of the text is different
- [ ] Non-semantic Issue: Spelling, grammar, or formatting changes.

Summary of issue:

This issue is for several possible refactors involving the voting processes described in Article VI.
- [x] The Simple Majority vote described in 6.C.1 describes a Relative Majority / Plurality vote, not a Simple Majority vote. Having both options (Relative Majority and Simple Majority) may be beneficial.
- [x] Combine language for Immediate and Secret Immediate Votes 6.B.3/6.B.4.
- [x] Combine "Fifty Percent", "Two Thirds", and "Three Quarters" votes.
- [x] Remove paper ballot requirements.
- [x] 6.D.1 may not be needed, depending on how votes in 6.C are described.
- [x] Rename "Alternative" vote (6.C.6) "Ranked Choice".
- [x] Remove "magic number" language in 6.C ("Below are listed four standard votes." - there are six, but better would be to remove this language entirely).
- [x] Clarify "Number of Votes Required" language. It seems strange to have it cover both the requirements for Quorum and for votes to pass.
- [ ] Language throughout the Constitution is inconsistent when describing votes' Quorum, Procedure, Number of Votes Required, and other characteristics. It would likely be best practice to define a consistent framework for discussing votes and replace current language with the new framework. 
  - Additionally, any votes should be modified as needed to reflect current practice.

**Comment by esoccoli** [comment]
Do we even need any of 6.C? The only necessary subsection is alternative vote, which could just be put elsewhere. The rest of them are common sense
