### ISSUE TITLE
Review Responsibilities of the Chairperson (5.C.2)

### ISSUE THREAD

**Issue by Sam-Cordry** [rhochgraf21/Constitution#39]
Check one:
- [ ] Semantic Issue: something about the meaning of the text is different
- [ ] Non-semantic Issue: Spelling, grammar, or formatting changes.

Summary of issue:
Talk with current and former Chairpersons about the accuracy of and any suggested changes to the constitutional responsibilities of the position.

**Comment by esoccoli** [comment]
- Add point about chair representing csh publicly
- add point about company visits
- Possible wording for company visits point: "coordinate collaboration between CSH and companies in the industry"
