### ISSUE TITLE
Alternative and Balloted Votes Require Paper Ballots (6.B.1, 6.B.2, 6.C.6)

### ISSUE THREAD

**Issue by rhochgraf21** [rhochgraf21/Constitution#4]
Check one:
- [X] Semantic Issue: something about the meaning of the text is different
- [ ] Non-semantic Issue: Spelling, grammar, or formatting changes.

Summary of issue:

Paper ballots are explicitly required for the votes defined in 6.B.1 and 6.B.2, however this is no longer current practice.

6.C.6 also references paper ballots.

**Comment by esoccoli** [comment]
This is being addressed by the voting amendment
