### ISSUE TITLE
Review Responsibilities of the Evaluations Director (5.C.3)

### ISSUE THREAD

**Issue by Sam-Cordry** [rhochgraf21/Constitution#40]
Check one:
- [ ] Semantic Issue: something about the meaning of the text is different
- [ ] Non-semantic Issue: Spelling, grammar, or formatting changes.

Summary of issue:
Talk with current and former Evaluations Directors about the accuracy of and any suggested changes to the constitutional responsibilities of the role.

**Comment by esoccoli** [comment]
Need to remove point about open houses to reflect current practice
