### ISSUE TITLE
Review Responsibilities of the Public Relations Director (5.C.5)

### ISSUE THREAD

**Issue by Sam-Cordry** [rhochgraf21/Constitution#42]
Check one:
- [ ] Semantic Issue: something about the meaning of the text is different
- [ ] Non-semantic Issue: Spelling, grammar, or formatting changes.

Summary of issue:
Talk with current and former Public Relations Directors about the accuracy of and any suggested changes to the constitutional responsibilities of the role.

**Comment by GODWSY1** [comment]
Talked with PR, further discussion is being conducted with past PR regarding this matter.
