### ISSUE TITLE
Review Responsibilities of the Financial Director (5.C.6)

### ISSUE THREAD

**Issue by Sam-Cordry** [rhochgraf21/Constitution#43]
Check one:
- [ ] Semantic Issue: something about the meaning of the text is different
- [ ] Non-semantic Issue: Spelling, grammar, or formatting changes.

Summary of issue:
Talk with current and former Financial Directors about the accuracy of and any suggested changes to the constitutional responsibilities of the role.

**Comment by esoccoli** [comment]
Determined that no changes need to be made
