### ISSUE TITLE
Review Responsibilities of the House Improvements Director (5.C.8)

### ISSUE THREAD

**Issue by Sam-Cordry** [rhochgraf21/Constitution#45]
Check one:
- [ ] Semantic Issue: something about the meaning of the text is different
- [ ] Non-semantic Issue: Spelling, grammar, or formatting changes.

Summary of issue:
Talk with current and former House Improvements Directors about the accuracy of and any suggested changes to the constitutional responsibilities of the role.

**Comment by Sam-Cordry** [comment]
Current Imps Director doesn't have any feedback except for the vagueness of subsection (b), which will need to be changed across all directorships (except OpComm) if it is changed.

**Comment by esoccoli** [comment]
Determined that no changes need to be made
