### ISSUE TITLE
5.D.2.A.4 People who pass into evals are offered "full membership"

### ISSUE THREAD

**Issue by esoccoli** [rhochgraf21/Constitution#49]
Check one:
- [X] Semantic Issue: something about the meaning of the text is different
- [ ] Non-semantic Issue: Spelling, grammar, or formatting changes.

Summary of issue:
5.D.2.A.4 discusses how, when someone passes intro evals, they are offered "full membership", which is not defined anywhere else and is ambiguous.

Also, 4.B.7 needs updating (active member resignations) to clarify that only members that have passed a spring evals can become alumni

**Comment by rhochgraf21** [comment]
- Consensus at the Constitution Rewrite meeting was that members that pass an Introductory Evaluations should be granted Active status.
  - We can keep the current language regarding frosh and spring evals (eg, that a person who has never passed a spring evals would have membership revoked in the case that they fail), without requiring an intermediary step (eg, "full membership"). 
  - We would _definitely need_ to change 4.B.7 for that case (as of right now, it appears _technically_ correct but rather unclear).

**Comment by Qelxiros** [comment]
The reference to "full membership" is actually in the section about selections. It seems that full membership is synonymous with Intro Member here. I'll open a PR, but this might need more discussion.
