### ISSUE TITLE
OpComm/RTPs vote by "simply majority vote" (5.D.3)

### ISSUE THREAD

**Issue by rhochgraf21** [rhochgraf21/Constitution#5]
Check one:
- [ ] Semantic Issue: something about the meaning of the text is different
- [X] Non-semantic Issue: Spelling, grammar, or formatting changes.

Summary of issue:

Should be Simple Majority Vote. Optimally reference the simple majority vote definition.

**Comment by Sam-Cordry** [comment]
This issue was resolved in the linked pull request by @GODWSY1.
