### ISSUE TITLE
5.D.2.A.2 - Return a document

### ISSUE THREAD

**Issue by eleanor-rose-t** [rhochgraf21/Constitution#50]
Check one:
- [X] Semantic Issue: something about the meaning of the text is different
- [ ] Non-semantic Issue: Spelling, grammar, or formatting changes.

Summary of issue:
In the Constitution, it says that each introductory process participant has to return a document with signatures. Packet is no longer on a paper document, it's online. Should this be changed?

Each Introductory Process participant, after the first week, is
given two (2) weeks to return a document that should contain a signature from all Active Members who
have passed a Membership Evaluation, all Active Resident Members, all Introductory Resident Members,
and ten (10) of any combination of the following:
 Alumni members
 Honorary members
 Advisory members

**Comment by mxmeinhold** [comment]
The packet application is well interpretable as a digital document. Specific wording to replace this might be rather awkward

**Comment by rhochgraf21** [comment]
nice find.

- "return a document" could be changed to something like "attain the signatures of"
- "should contain a signature from all Active members" could also be a phrashing warranting modification
