### ISSUE TITLE
Seemingly unnecessary qualification for becoming an RTP (5.D.3.B)

### ISSUE THREAD

**Issue by esoccoli** [rhochgraf21/Constitution#60]
Check one:
- [x] Semantic Issue: something about the meaning of the text is different
- [ ] Non-semantic Issue: Spelling, grammar, or formatting changes.

Summary of issue:
Subsection A states that to become an RTP, you must be living on floor at that time, or have lived on floor at some point within the 12 months prior. Immediately after that, subsection B says that the current RTPs can grant exemptions for that requirement. At that point, it seems like the requirement itself is arbitrary, since the RTPs can just exempt people who dont meet it if they want to

**Comment by Sam-Cordry** [comment]
Talked about this, and change scope to changing qualifications to be "current Active member" and adding Prior RTPs section.
