### ISSUE TITLE
2.C Consider Reworking the way Maintainers are Defined

### ISSUE THREAD

**Issue by esoccoli** [rhochgraf21/Constitution#62]
Check one:
- [X] Semantic Issue: something about the meaning of the text is different
- [ ] Non-semantic Issue: Spelling, grammar, or formatting changes.

Summary of issue:
Way too many sections, we don't need 5 subsections to define maintainers

**Comment by Sam-Cordry** [comment]
Partially addressed by #97 (PR associated with #85).

**Comment by esoccoli** [comment]
Decided to leave overall formatting as is
