### ISSUE TITLE
Fix Financial Information/Calculations in 5.D.1.C 

### ISSUE THREAD

**Issue by rhochgraf21** [rhochgraf21/Constitution#7]
Check one:
- [X] Semantic Issue: something about the meaning of the text is different
- [ ] Non-semantic Issue: Spelling, grammar, or formatting changes.

Summary of issue:

- The table in 5.D.1.C says 10% is reserved for Accum, however only 5% is. 
- The total operational budget calculation is incorrect.
- There are 55 on-floor members, not 72.

Additionally, it may be worth discussing removing the "suggested operational budget" section.

**Comment by Loerb01** [comment]
It seems strange to have a suggested operational budget in a constitution. A constitution is usually considered a binding document, and to put non-binding language in strikes me as not well thought out. Another option would be to change the budget allocation into something more binding, with a way to change it (eboard vote? house vote?).
