### ISSUE TITLE
Generalize resignations?

### ISSUE THREAD

**Issue by esoccoli** [rhochgraf21/Constitution#70]
Check one:
- [ ] Semantic Issue: something about the meaning of the text is different
- [ ] Non-semantic Issue: Spelling, grammar, or formatting changes.

Summary of issue:
Resignations are mostly the same for all membership types, so it can probably be condensed. However, there would be some edge cases that need to be addressed, but it should be considered

**Comment by esoccoli** [comment]
Should be drafted before we discuss it

**Comment by Sam-Cordry** [comment]
Decided to not pursue this particular change.
