### ISSUE TITLE
Put the intro process in its own section

### ISSUE THREAD

**Issue by esoccoli** [rhochgraf21/Constitution#73]
Check one:
- [ ] Semantic Issue: something about the meaning of the text is different
- [ ] Non-semantic Issue: Spelling, grammar, or formatting changes.

Summary of issue:
Descriptions of the intro process is like 1/3 of "Operations of the Evals Directorship". It should be moved into its own section for organization and also to make Operations of Evals more readable

**Comment by Sam-Cordry** [comment]
Addressed by #76.
