### ISSUE TITLE
Reformat Membership Section

### ISSUE THREAD

**Issue by esoccoli** [rhochgraf21/Constitution#76]
Check one:
- [ ] Semantic Issue: something about the meaning of the text is different
- [X] Non-semantic Issue: Spelling, grammar, or formatting changes.

Summary of issue:
Reformat the membership section so info about each membership type is structured in the same way as the term definitions in that section

ie:

Qualifications: ...
Selection: ...
 Expectations: ...
etc.

**Comment by Sam-Cordry** [comment]
Directly related to #70.

**Comment by Sam-Cordry** [comment]
Decided to keep the current format for lack of a better one.
