### ISSUE TITLE
Clarify State of Membership Status During Conditional (5.D.2.C.1.B)

### ISSUE THREAD

**Issue by rhochgraf21** [rhochgraf21/Constitution#8]
Check one:
- [X] Semantic Issue: something about the meaning of the text is different
- [ ] Non-semantic Issue: Spelling, grammar, or formatting changes.

Summary of issue:

The membership status of a member that is given a conditional is likely Active, though this is unclear and would be best to clarify.

- An active member remains an active member if they have passed their most recent membership evaluation. If the membership evaluation is ongoing, does that mean the most recent evaluation was passed or was not passed?

**Comment by mxmeinhold** [comment]
General interpretation is that a conditional is deferred evaluation, so they maintain their current status until the conditional is resolved. So an intro member remains an intro member, and an active member remains active. For the purposes of the following operating session, someone on conditional might elect to be considered Alumni, e.g. they wouldn't be held to the requirements of the new operating session, only to their conditional

**Comment by rhochgraf21** [comment]
We discussed this in detail at a Constitution Rewrite meeting. Consensus was that deferring evaluations per mxmeinhold above is the preferred, but that the language in this section is in need of clarification.

**Comment by esoccoli** [comment]
Need to update wording
