### ISSUE TITLE
4 - Move evals processes into the proper membership section

### ISSUE THREAD

**Issue by esoccoli** [rhochgraf21/Constitution#88]
Check one:
- [ ] Semantic Issue: something about the meaning of the text is different
- [X] Non-semantic Issue: Spelling, grammar, or formatting changes.

Summary of issue:
Currently, all the evals processes are described under operations of the evals director. It would make more sense to put those descriptions in the membership section that is impacted by the evaluation (ie: intro evals into intro membership, spring evals into active membership)

**Comment by esoccoli** [comment]
Need to decide how we want to structure membership sections before these changes can be made

**Comment by rhochgraf21** [comment]
Issue covered by #147, so closing. reopen as needed.
